/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XtAgDDmXRoY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

interface CodeBlockProps {
  code: string;
}

export const CodeBlock: React.FC<CodeBlockProps> = ({ code }) => {
  return (
    <section key="1" className="bg-gray-100 p-4 rounded-lg mb-4">
      <div className="text-xs text-gray-500">Language: JSX</div>
      <div className="bg-gray-50 p-0 rounded-lg">
        <pre className="p-6 text-sm font-mono rounded-lg w-full overflow-x-auto">
          <code className="rounded-lg">
            {code}
          </code>
        </pre>
        <div className="absolute top-0 right-0 p-2">
          <CopyIcon className="h-6 w-6 text-gray-500 cursor-pointer" />
        </div>
      </div>
    </section>
  )
}

function CopyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
      <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
    </svg>
  )
}
